import {
  Class,
  getNormalizedFilterValue,
  Language,
  Rarity,
  Release,
  type ReleaseInfo,
  ReleaseType,
  Talent,
} from "@flesh-and-blood/types";

const ALL_LANGUAGES_OLD = [
  Language.English,
  Language.French,
  Language.German,
  Language.Italian,
  Language.Japanese,
  Language.Spanish,
];

const ALL_LANGUAGES = [Language.English, Language.French, Language.Japanese];

// One record per release, in release order. Printings sort newest first by a
// release's place here, and a release with no date sorts behind every dated one.
export const releases: ReleaseInfo[] = [
  {
    cards: 30,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GJG7Z4WGWSZ95FY74KX4M557" },
    ],
    heroIdentifiers: ["ira-crimson-haze"],
    languages: ALL_LANGUAGES_OLD,
    release: Release.IraWelcomeDeck,
    relatedReleases: [],
    releaseDate: "2019-08-31 12:00",
    releaseType: ReleaseType.WelcomeDeck,
    setIdentifiers: ["ira"],
    talents: [],
  },
  {
    cards: 60,
    classes: [Class.Guardian],
    deckLinks: [],
    heroIdentifiers: ["bravo-showstopper"],
    languages: [Language.English],
    release: Release.BravoHeroDeck,
    relatedReleases: [],
    releaseDate: "2019-10-11 12:00",
    releaseType: ReleaseType.HeroDeck,
    setIdentifiers: ["bvo"],
    talents: [],
  },
  {
    cards: 60,
    classes: [Class.Warrior],
    deckLinks: [],
    heroIdentifiers: ["dorinthea-ironsong"],
    languages: [Language.English],
    release: Release.DorintheaHeroDeck,
    relatedReleases: [],
    releaseDate: "2019-10-11 12:00",
    releaseType: ReleaseType.HeroDeck,
    setIdentifiers: ["tea"],
    talents: [],
  },
  {
    cards: 60,
    classes: [Class.Ninja],
    deckLinks: [],
    heroIdentifiers: ["katsu-the-wanderer"],
    languages: [Language.English],
    release: Release.KatsuHeroDeck,
    relatedReleases: [],
    releaseDate: "2019-10-11 12:00",
    releaseType: ReleaseType.HeroDeck,
    setIdentifiers: ["ksu"],
    talents: [],
  },
  {
    cards: 60,
    classes: [Class.Brute],
    deckLinks: [],
    heroIdentifiers: ["rhinar-reckless-rampage"],
    languages: [Language.English],
    release: Release.RhinarHeroDeck,
    relatedReleases: [],
    releaseDate: "2019-10-11 12:00",
    releaseType: ReleaseType.HeroDeck,
    setIdentifiers: ["rnr"],
    talents: [],
  },
  {
    cards: 226,
    classes: [Class.Brute, Class.Guardian, Class.Ninja, Class.Warrior],
    deckLinks: [],
    draft: {
      picksPerPack: 15,
    },
    heroIdentifiers: [
      "bravo",
      "bravo-showstopper",
      "dorinthea",
      "dorinthea-ironsong",
      "katsu",
      "katsu-the-wanderer",
      "rhinar",
      "rhinar-reckless-rampage",
    ],
    languages: [Language.English],
    release: Release.WelcomeToRathe,
    relatedReleases: [
      Release.BravoHeroDeck,
      Release.DorintheaHeroDeck,
      Release.KatsuHeroDeck,
      Release.RhinarHeroDeck,
    ],
    releaseDate: "2019-10-11 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["wtr"],
    talents: [],
  },
  {
    cards: 219,
    classes: [Class.Mechanologist, Class.Ranger, Class.Runeblade, Class.Wizard],
    deckLinks: [],
    draft: {
      picksPerPack: 15,
    },
    heroIdentifiers: [
      "azalea",
      "azalea-ace-in-the-hole",
      "dash",
      "dash-inventor-extraordinaire",
      "kano",
      "kano-dracai-of-aether",
      "viserai",
      "viserai-rune-blood",
    ],
    languages: [Language.English],
    release: Release.ArcaneRising,
    relatedReleases: [],
    releaseDate: "2020-03-27 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["arc"],
    talents: [],
  },
  {
    cards: 194,
    classes: [
      Class.Brute,
      Class.Guardian,
      Class.Mechanologist,
      Class.Merchant,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    deckLinks: [],
    heroIdentifiers: [
      "benji-the-piercing-wind",
      "data-doll-mkii",
      "ira-crimson-haze",
      "kassai-cintari-sellsword",
      "kavdaen-trader-of-skins",
      "kayo-berserker-runt",
      "shiyana-diamond-gemini",
    ],
    languages: [Language.English],
    release: Release.CrucibleOfWar,
    relatedReleases: [],
    releaseDate: "2020-08-28 12:00",
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["cru"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7FD2B3YQAMR8NJ4B3M58H96" },
    ],
    heroIdentifiers: ["boltyn"],
    languages: [Language.English],
    release: Release.BoltynBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-05-07 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["bol"],
    talents: [Talent.Light],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7FDVRZP35DFWBRK64AG5TKQ" },
    ],
    heroIdentifiers: ["chane"],
    languages: [Language.English],
    release: Release.ChaneBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-05-07 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["chn"],
    talents: [Talent.Shadow],
  },
  {
    cards: 40,
    classes: [Class.Brute],
    languages: [Language.English],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7B1T1D1M2DAM61K876VJBDK" },
    ],
    heroIdentifiers: ["levia"],
    release: Release.LeviaBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-05-07 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["lev"],
    talents: [Talent.Shadow],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7FCP2N7N0MNHWAH6JTP0KFN" },
    ],
    heroIdentifiers: ["prism"],
    languages: [Language.English],
    relatedReleases: [],
    releaseDate: "2021-05-07 12:00",
    release: Release.PrismBlitzDeck,
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["psm"],
    talents: [Talent.Light],
  },
  {
    cards: 307,
    classes: [Class.Brute, Class.Illusionist, Class.Runeblade, Class.Warrior],
    deckLinks: [],
    draft: {
      picksPerPack: 15,
    },
    heroIdentifiers: [
      "boltyn",
      "ser-boltyn-breaker-of-dawn",
      "chane",
      "chane-bound-by-shadow",
      "levia",
      "levia-shadowborn-abomination",
      "prism",
      "prism-sculptor-of-arc-light",
    ],
    languages: [Language.English],
    release: Release.Monarch,
    relatedReleases: [
      Release.BoltynBlitzDeck,
      Release.ChaneBlitzDeck,
      Release.LeviaBlitzDeck,
      Release.PrismBlitzDeck,
    ],
    releaseDate: "2021-05-07 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["mon"],
    talents: [Talent.Light, Talent.Shadow],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7K4D304QQCZZSBT7ABCX4XC" },
    ],
    heroIdentifiers: ["briar"],
    languages: [Language.English],
    release: Release.BriarBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-11-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    talents: [Talent.Elemental, Talent.Earth, Talent.Lightning],
    setIdentifiers: ["bri"],
  },
  {
    cards: 40,
    classes: [Class.Ranger],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7K3WGPVKVDXG2J013GXSXNP" },
    ],
    heroIdentifiers: ["lexi"],
    languages: [Language.English],
    release: Release.LexiBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-11-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["lxi"],
    talents: [Talent.Elemental, Talent.Ice, Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7K464J7VS0K7HKW5E395TBK" },
    ],
    heroIdentifiers: ["oldhim"],
    languages: [Language.English],
    release: Release.OldhimBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-11-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["old"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice],
  },
  {
    cards: 238,
    classes: [Class.Guardian, Class.Ranger, Class.Runeblade],
    deckLinks: [],
    draft: {
      picksPerPack: 15,
    },
    heroIdentifiers: [
      "briar",
      "briar-warden-of-thorns",
      "lexi",
      "lexi-livewire",
      "oldhim",
      "oldhim-grandfather-of-eternity",
    ],
    languages: [Language.English],
    release: Release.TalesOfAria,
    relatedReleases: [
      Release.BriarBlitzDeck,
      Release.LexiBlitzDeck,
      Release.OldhimBlitzDeck,
    ],
    releaseDate: "2021-09-24 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["ele"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice, Talent.Lightning],
  },
  {
    cards: 198,
    classes: [
      Class.Brute,
      Class.Guardian,
      Class.Illusionist,
      Class.Mechanologist,
      Class.Merchant,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    deckLinks: [],
    heroIdentifiers: [
      "genis-wotchuneed",
      "bravo-star-of-the-show",
      "valda-brightaxe",
    ],
    languages: [Language.English],
    release: Release.Everfest,
    relatedReleases: [],
    releaseDate: "2022-02-04 12:00",
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["evr"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice, Talent.Lightning],
  },
  {
    cards: 423,
    classes: [
      Class.Brute,
      Class.Guardian,
      Class.Mechanologist,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    deckLinks: [],
    heroIdentifiers: [
      "azalea",
      "azalea-ace-in-the-hole",
      "benji-the-piercing-wind",
      "bravo",
      "bravo-showstopper",
      "dash",
      "dash-inventor-extraordinaire",
      "data-doll-mkii",
      "dorinthea",
      "dorinthea-ironsong",
      "ira-crimson-haze",
      "kassai-cintari-sellsword",
      "katsu",
      "katsu-the-wanderer",
      "kayo-berserker-runt",
      "rhinar",
      "rhinar-reckless-rampage",
      "viserai",
      "viserai-rune-blood",
      "kano",
      "kano-dracai-of-aether",
    ],
    languages: [Language.English],
    release: Release.HistoryPack1,
    relatedReleases: [],
    releaseDate: "2022-05-06 12:00",
    releaseType: ReleaseType.HistoryPack,
    setIdentifiers: ["1hp", "hp1"],
    talents: [],
  },
  {
    cards: 80,
    classes: [Class.Brute, Class.Warrior],
    deckLinks: [
      {
        name: "Dorinthea",
        url: "https://fabrary.net/decks/01GA4WTNSD12YTQB4FY8EYYNG5",
      },
      {
        name: "Rhinar",
        url: "https://fabrary.net/decks/01GA4WZKX9VEWKKPX7Y7H3MG1F",
      },
    ],
    heroIdentifiers: ["dorinthea-quicksilver-prodigy", "rhinar"],
    languages: [Language.English],
    release: Release.ClassicBattlesRhinarDorinthea,
    relatedReleases: [],
    releaseDate: "2022-05-27 12:00",
    releaseType: ReleaseType.ClassicBattles,
    setIdentifiers: ["dvr", "rvd"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G76H1R1ERRBRKS7RVCQAB8RX" },
    ],
    heroIdentifiers: ["dromai"],
    languages: [Language.English],
    relatedReleases: [],
    releaseDate: "2022-06-24 12:00",
    release: Release.DromaiBlitzDeck,
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["dro"],
    talents: [Talent.Draconic],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G76H7RG7GN5ZA10F3BJBH740" },
    ],
    heroIdentifiers: ["fai"],
    languages: [Language.English],
    release: Release.FaiBlitzDeck,
    relatedReleases: [],
    releaseDate: "2022-06-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["fai"],
    talents: [Talent.Draconic],
  },
  {
    cards: 226,
    classes: [Class.Illusionist, Class.Ninja, Class.Wizard],
    deckLinks: [],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "dromai",
      "dromai-ash-artist",
      "fai",
      "fai-rising-rebellion",
      "iyslander",
      "iyslander-stormbind",
    ],
    languages: [Language.English],
    release: Release.Uprising,
    relatedReleases: [Release.DromaiBlitzDeck, Release.FaiBlitzDeck],
    releaseDate: "2022-06-24 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["upr"],
    talents: [Talent.Draconic, Talent.Elemental, Talent.Ice],
  },
  {
    cards: 247,
    classes: [
      Class.Assassin,
      Class.Brute,
      Class.Guardian,
      Class.Illusionist,
      Class.Mechanologist,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    deckLinks: [],
    heroIdentifiers: [
      "arakni",
      "arakni-huntsman",
      "emperor-dracai-of-aesir",
      "yoji-royal-protector",
    ],
    languages: [Language.English],
    release: Release.Dynasty,
    relatedReleases: [],
    releaseDate: "2022-11-11 12:00",
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["dyn"],
    talents: [Talent.Royal],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW25PNWBW2FPDHRNTPSET0GT" },
    ],
    heroIdentifiers: ["arakni-solitary-confinement"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.ArakniBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ara"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ranger],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW26RNH1Q1J0S1VFXPN609S2" },
    ],
    heroIdentifiers: ["azalea"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.AzaleaBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["azl"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW28622XSVAK7H9RXZVAVKM0" },
    ],
    heroIdentifiers: ["benji-the-piercing-wind"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.BenjiBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ben"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW28TF5FXFKJ5CGRNXB84CG6" },
    ],
    heroIdentifiers: ["katsu"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.KatsuBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["kat"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ranger],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW29DPNZ3XVBJQHHFQHHHDGN" },
    ],
    heroIdentifiers: ["riptide"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.RiptideBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["rip"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW2945GHPH2YSX3FTS7HCBT1" },
    ],
    heroIdentifiers: ["uzuri"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.UzuriBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["uzu"],
    talents: [],
  },
  {
    cards: 239,
    classes: [Class.Assassin, Class.Ranger, Class.Ninja],
    deckLinks: [],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "arakni-solitary-confinement",
      "azalea",
      "azalea-ace-in-the-hole",
      "benji-the-piercing-wind",
      "katsu",
      "katsu-the-wanderer",
      "riptide",
      "riptide-lurker-of-the-deep",
      "uzuri",
      "uzuri-switchblade",
    ],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.Outsiders,
    relatedReleases: [
      Release.ArakniBlitzDeck,
      Release.AzaleaBlitzDeck,
      Release.BenjiBlitzDeck,
      Release.KatsuBlitzDeck,
      Release.RiptideBlitzDeck,
      Release.UzuriBlitzDeck,
    ],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["out"],
    talents: [],
  },
  {
    cards: 236,
    classes: [Class.Illusionist, Class.Runeblade, Class.Warrior, Class.Brute],
    deckLinks: [],
    heroIdentifiers: [
      "prism-advent-of-thrones",
      "prism-awakener-of-sol",
      "vynnset",
      "vynnset-iron-maiden",
      "boltyn",
      "ser-boltyn-breaker-of-dawn",
      "levia",
      "levia-shadowborn-abomination",
    ],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.DuskTillDawn,
    relatedReleases: [],
    releaseDate: "2023-07-14 12:00",
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["dtd"],
    talents: [Talent.Light, Talent.Shadow],
  },
  {
    cards: 107,
    classes: [Class.Mechanologist, Class.Bard, Class.Guardian, Class.Ninja],
    deckLinks: [
      {
        name: "Brevant",
        url: "https://fabrary.net/decks/01HAXKPFH7ZHPDEJZH967VNRW6",
      },
      {
        name: "Ira",
        url: "https://fabrary.net/decks/01HAXKZMTRN4FR7CFTQA11A70N",
      },
      {
        name: "Melody",
        url: "https://fabrary.net/decks/01HAXKSFPXGCEH99PDZJ32V4N9",
      },
      {
        name: "Teklovossen",
        url: "https://fabrary.net/decks/01HAXKZMTRN4FR7CFTQA11A70N",
      },
    ],
    heroIdentifiers: [
      "professor-teklovossen",
      "melody-sing-along",
      "brevant-civic-protector",
      "ira-crimson-haze",
    ],
    languages: [Language.English],
    release: Release.RoundTheTable,
    relatedReleases: [],
    releaseDate: "2023-09-29 12:00",
    releaseType: ReleaseType.RoundTheTable,
    talents: [],
    setIdentifiers: ["tcc"],
  },
  {
    cards: 251,
    classes: [Class.Mechanologist],
    deckLinks: [],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "dash-io",
      "dash-database",
      "maxx-the-hype-nitro",
      "maxx-nitro",
      "teklovossen",
      "teklovossen-esteemed-magnate",
    ],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.BrightLights,
    relatedReleases: [],
    releaseDate: "2023-10-06 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["evo"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3J1X1NQ9TB9RTVWV42JG46" },
    ],
    heroIdentifiers: ["betsy"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.BetsyBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["bet"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3SHBEQBRECYK6ZN1CHRADR" },
    ],
    heroIdentifiers: ["kassai"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.KassaiBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ksi"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Brute],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3HK89NA910SK3FQV84H46Z" },
    ],
    heroIdentifiers: ["kayo"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.KayoBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["kyo"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3GP5ZJ1NRC0XBYNE45XQE8" },
    ],
    heroIdentifiers: ["olympia"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.OlympiaBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ola"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Brute],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3Q4GBDMEFSX98HEN9ET308" },
    ],
    heroIdentifiers: ["rhinar"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.RhinarBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["rhi"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3K8ZV7KBRRJKPHW4B13J1K" },
    ],
    heroIdentifiers: ["victor-goldmane"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.VictorBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["vic"],
    talents: [],
  },
  {
    cards: 255,
    classes: [Class.Brute, Class.Guardian, Class.Warrior],
    deckLinks: [],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "kassai",
      "kassai-of-the-golden-sand",
      "betsy",
      "betsy-skin-in-the-game",
      "kayo",
      "kayo-armed-and-dangerous",
      "olympia",
      "olympia-prized-fighter",
      "rhinar",
      "rhinar-reckless-rampage",
      "victor-goldmane",
      "victor-goldmane-high-and-mighty",
    ],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.HeavyHitters,
    relatedReleases: [
      Release.BetsyBlitzDeck,
      Release.KassaiBlitzDeck,
      Release.KayoBlitzDeck,
      Release.OlympiaBlitzDeck,
      Release.RhinarBlitzDeck,
      Release.VictorBlitzDeck,
    ],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["hvy"],
    talents: [],
  },
  {
    cards: 66,
    classes: [Class.Brute],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HWNCK2BYPVKK6701052YYXMZ" },
    ],
    heroIdentifiers: ["kayo-armed-and-dangerous"],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckKayo,
    relatedReleases: [],
    releaseDate: "2024-05-03 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["ako"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HX5Z23X2PRQCJ100FP4CAZGK" },
    ],
    heroIdentifiers: ["enigma"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.EnigmaBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-05-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["eng"],
    talents: [Talent.Mystic],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HX5Z4BD3TRMS3CP1ME4ZP3T6" },
    ],
    heroIdentifiers: ["nuu"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.NuuBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-05-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["nuu"],
    talents: [Talent.Mystic],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HX5Z395FD35CM24QCJQKJER1" },
    ],
    heroIdentifiers: ["zen"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.ZenBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-05-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["zen"],
    talents: [Talent.Mystic],
  },
  {
    cards: 239,
    classes: [Class.Assassin, Class.Illusionist, Class.Ninja],
    deckLinks: [],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "enigma",
      "enigma-ledger-of-ancestry",
      "enigma-new-moon",
      "nuu",
      "nuu-alluring-desire",
      "zen",
      "zen-tamer-of-purpose",
    ],
    languages: ALL_LANGUAGES_OLD,
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.PartTheMistveil,
    relatedReleases: [
      Release.EnigmaBlitzDeck,
      Release.NuuBlitzDeck,
      Release.ZenBlitzDeck,
    ],
    releaseDate: "2024-05-31 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["mst"],
    talents: [Talent.Mystic],
  },
  {
    cards: 66,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J202NH0RG8S0V8WXH1FWB2AH" },
    ],
    heroIdentifiers: ["ser-boltyn-breaker-of-dawn"],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckBoltyn,
    relatedReleases: [],
    releaseDate: "2024-07-12 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["asb"],
    talents: [Talent.Light],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J45SYSM2ZERW6CWY283ZAT1S" },
    ],
    heroIdentifiers: ["aurora"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.FirstStrikeAurora,
    relatedReleases: [],
    releaseDate: "2024-08-01 12:00",
    releaseType: ReleaseType.FirstStrike,
    setIdentifiers: ["aur"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J45SWXNDV5XD8PTBACAV8NZ1" },
    ],
    heroIdentifiers: ["terra"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.FirstStrikeTerra,
    relatedReleases: [],
    releaseDate: "2024-08-01 12:00",
    releaseType: ReleaseType.FirstStrike,
    setIdentifiers: ["ter"],
    talents: [Talent.Earth],
  },
  {
    cards: 66,
    classes: [Class.Ranger],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J3GKKSTM773CW7BG3RRJ5FJH" },
    ],
    heroIdentifiers: ["azalea-ace-in-the-hole"],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckAzalea,
    relatedReleases: [],
    releaseDate: "2024-08-02 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["aaz"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J68KF1TFNN62TC0G7M993FTY" },
    ],
    heroIdentifiers: ["aurora"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.AuroraBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-09-20 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["aua"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J68KFRMJFKRQYJJ7THG1GMTB" },
    ],
    heroIdentifiers: ["florian"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.FlorianBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-09-20 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["flr"],
    talents: [Talent.Earth],
  },
  {
    cards: 40,
    classes: [Class.Wizard],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J68KGA3JVKFHEXGKYW0441CY" },
    ],
    heroIdentifiers: ["oscilio"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.OscilioBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-09-20 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["osc"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Wizard],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J68KGT3XD3HMVVRFT174QNMF" },
    ],
    heroIdentifiers: ["verdance"],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.VerdanceBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-09-20 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ver"],
    talents: [Talent.Earth],
  },
  {
    cards: 258,
    classes: [Class.Runeblade, Class.Wizard],
    deckLinks: [],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "aurora",
      "aurora-shooting-star",
      "florian",
      "florian-rotwood-harbinger",
      "oscilio",
      "oscilio-constella-intelligence",
      "verdance",
      "verdance-thorn-of-the-rose",
    ],
    languages: ALL_LANGUAGES_OLD,
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.Rosetta,
    relatedReleases: [
      Release.AuroraBlitzDeck,
      Release.FlorianBlitzDeck,
      Release.OscilioBlitzDeck,
      Release.VerdanceBlitzDeck,
    ],
    releaseDate: "2024-09-20 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["ros"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Lightning],
  },
  {
    cards: 66,
    classes: [Class.Mechanologist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J9822H5PANJAFQVMC4TPK4Z1" },
    ],
    heroIdentifiers: ["dash-io"],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckDash,
    relatedReleases: [],
    releaseDate: "2024-10-18 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["aio"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01JCPPENK52DTRBJZMWQF8S0X2" },
    ],
    heroIdentifiers: ["jarl-vetreidi"],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckOriginsJarl,
    relatedReleases: [],
    releaseDate: "2024-11-29 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["ajv"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    deckLinks: [],
    heroIdentifiers: ["arakni"],
    languages: ALL_LANGUAGES_OLD,
    release: Release.ArakniBlitzDeckARK,
    relatedReleases: [],
    releaseDate: "2025-01-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ark"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    deckLinks: [],
    heroIdentifiers: ["arakni-web-of-deceit"],
    languages: ALL_LANGUAGES_OLD,
    release: Release.ArakniWebOfDeceitBlitzDeck,
    relatedReleases: [],
    releaseDate: "2025-01-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["wod"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    deckLinks: [],
    heroIdentifiers: ["cindra"],
    languages: ALL_LANGUAGES_OLD,
    release: Release.CindraBlitzDeck,
    relatedReleases: [],
    releaseDate: "2025-01-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["cin"],
    talents: [Talent.Draconic, Talent.Royal],
  },
  {
    cards: 40,
    classes: [Class.Warrior],
    deckLinks: [],
    heroIdentifiers: ["fang"],
    languages: ALL_LANGUAGES_OLD,
    release: Release.FangBlitzDeck,
    relatedReleases: [],
    releaseDate: "2025-01-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["fng"],
    talents: [Talent.Draconic, Talent.Royal],
  },
  {
    cards: 265,
    classes: [Class.Assassin, Class.Ninja, Class.Warrior],
    deckLinks: [],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "arakni-marionette",
      "arakni-web-of-deceit",
      "cindra",
      "cindra-dracai-of-retribution",
      "fang",
      "fang-dracai-of-blades",
    ],
    languages: ALL_LANGUAGES_OLD,
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.TheHunted,
    relatedReleases: [
      Release.ArakniBlitzDeckARK,
      Release.ArakniWebOfDeceitBlitzDeck,
      Release.CindraBlitzDeck,
      Release.FangBlitzDeck,
    ],
    releaseDate: "2025-01-31 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["hnt"],
    talents: [Talent.Chaos, Talent.Draconic, Talent.Royal],
  },
  {
    cards: 28,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01JN2DEG4X2V8DVMCWFBWQTTSC" },
    ],
    heroIdentifiers: ["aurora-shooting-star"],
    languages: [Language.English, Language.French, Language.Japanese],
    release: Release.ArmoryDeckAurora,
    relatedReleases: [],
    releaseDate: "2025-03-14 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["ast"],
    talents: [Talent.Elemental, Talent.Lightning],
  },
  {
    cards: 28,
    classes: [Class.Mechanologist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01JRH0631MH5A9JPVGTP3TKJXN" },
    ],
    heroIdentifiers: ["maxx-the-hype-nitro"],
    languages: [Language.English, Language.French, Language.Japanese],
    release: Release.ArmoryDeckMaxx,
    relatedReleases: [],
    releaseDate: "2025-04-17 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["amx"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Necromancer, Class.Pirate],
    deckLinks: [
      { url: "https://fabrary.net/decks/01JVYZ0NCHP49HAP40C23P14E3" },
    ],
    heroIdentifiers: ["gravy-bones", "gravy-bones-shipwrecked-looter"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckGravyBones,
    relatedReleases: [],
    releaseDate: "2025-05-30 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["agb"],
    talents: [],
  },
  {
    cards: 265,
    classes: [
      Class.Mechanologist,
      Class.Necromancer,
      Class.Pirate,
      Class.Ranger,
      Class.Thief,
    ],
    deckLinks: [],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "gravy-bones",
      "gravy-bones-shipwrecked-looter",
      "marlynn",
      "marlynn-treasure-hunter",
      "puffin",
      "puffin-hightail",
      "scurv-stowaway",
    ],
    languages: ALL_LANGUAGES,
    raritiesExcludedInLimited: [Rarity.Fabled, Rarity.Legendary],
    release: Release.HighSeas,
    relatedReleases: [],
    releaseDate: "2025-06-06 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["sea"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01JZ97KZ5TQV8E0FYMAM0XVNX7" },
    ],
    heroIdentifiers: ["ira-scarlet-revenger"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckIra,
    relatedReleases: [],
    releaseDate: "2025-07-11 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["asr"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01K0ZQGQYJPH6B90VNT3GJ8C7Q" },
    ],
    heroIdentifiers: ["viserai-rune-blood"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckLegendsViserai,
    relatedReleases: [],
    releaseDate: "2025-07-24 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["avs"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Illusionist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01K0ZQ8FVR8DQB7YC9N7KAB7N8" },
    ],
    heroIdentifiers: ["prism-sculptor-of-arc-light"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckLegendsPrism,
    relatedReleases: [],
    releaseDate: "2025-07-24 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["apr"],
    talents: [Talent.Light],
  },
  {
    cards: 130,
    classes: [Class.Guardian],
    deckLinks: [],
    heroIdentifiers: ["valda-brightaxe", "valda-seismic-impact"],
    languages: ALL_LANGUAGES,
    release: Release.MasteryPackGuardian,
    relatedReleases: [],
    releaseDate: "2025-08-08 12:00",
    releaseType: ReleaseType.MasteryPack,
    setIdentifiers: ["mpg"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01K1GBSGB17GT925NVJ0PM0G9Y" },
    ],
    heroIdentifiers: ["bravo-flattering-showman"],
    languages: ALL_LANGUAGES,
    release: Release.BravoDemoDeck,
    relatedReleases: [],
    releaseDate: "2025-08-08 12:00",
    releaseType: ReleaseType.WelcomeDeck,
    setIdentifiers: ["bdd"],
    talents: [],
  },
  {
    cards: 107,
    classes: [Class.Guardian],
    deckLinks: [],
    heroIdentifiers: [
      "bolfar-bear-hands",
      "bravo-flattering-showman",
      "fightmaster-kox",
      "groundbreaker-crix",
      "reya-the-unyielding",
      "victor-goldmane-match-fixer",
    ],
    languages: [Language.English],
    release: Release.SmashPalace,
    relatedReleases: [],
    releaseDate: "2025-09-29 12:00",
    releaseType: ReleaseType.BoxSet,
    talents: [],
    setIdentifiers: ["smp"],
  },
  {
    cards: 276,
    classes: [Class.Brute, Class.Guardian],
    deckLinks: [],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "kayo-strong-arm",
      "kayo-underhanded-cheat",
      "lyath-goldmane",
      "lyath-goldmane-vile-savant",
      "pleiades",
      "pleiades-superstar",
      "tuffnut",
      "tuffnut-bumbling-hulkster",
    ],
    languages: ALL_LANGUAGES,
    raritiesExcludedInLimited: [Rarity.Fabled, Rarity.Legendary],
    release: Release.SuperSlam,
    relatedReleases: [],
    releaseDate: "2025-09-26 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["sup"],
    talents: [Talent.Revered, Talent.Reviled],
  },
  {
    cards: 30,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01K4XX1ERKXRYW8XHWE9BTAS4W" },
    ],
    heroIdentifiers: ["pleiades", "pleiades-superstar"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckPleiades,
    relatedReleases: [],
    releaseDate: "2025-09-19 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["aps"],
    talents: [Talent.Revered],
  },
  {
    cards: 30,
    classes: [Class.Brute],
    deckLinks: [
      { url: "https://fabrary.net/decks/01K74RSFG9RTVPVN534DZPJJNQ" },
    ],
    heroIdentifiers: ["rhinar-reckless-rampage"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckRhinar,
    relatedReleases: [],
    releaseDate: "2025-11-14 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["arr"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Assassin],
    deckLinks: [
      { url: "https://fabrary.net/decks/01K74RXDPRPJT9YWGFVAPHECDF" },
    ],
    heroIdentifiers: ["arakni-5lp3d-7hru-7h3-cr4x"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckArakni,
    relatedReleases: [],
    releaseDate: "2025-12-15 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["aac"],
    talents: [Talent.Chaos],
  },
  {
    cards: 348,
    classes: [
      Class.Assassin,
      Class.Brute,
      Class.Generic,
      Class.Guardian,
      Class.Illusionist,
      Class.Mechanologist,
      Class.Necromancer,
      Class.Ninja,
      Class.Pirate,
      Class.Ranger,
      Class.Runeblade,
      Class.Thief,
      Class.Warrior,
      Class.Wizard,
    ],
    deckLinks: [],
    heroIdentifiers: [],
    languages: ALL_LANGUAGES,
    release: Release.CompendiumOfRathe,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["pen"],
    talents: [
      Talent.Chaos,
      Talent.Draconic,
      Talent.Earth,
      Talent.Elemental,
      Talent.Ice,
      Talent.Light,
      Talent.Lightning,
      Talent.Mystic,
      Talent.Revered,
      Talent.Reviled,
      Talent.Shadow,
    ],
  },
  {
    cards: 40,
    chapter: 2,
    classes: [Class.Assassin],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KFWFQYASKA6C1FGXXB0E8EGE" },
    ],
    heroIdentifiers: ["arakni-web-of-deceit"],
    languages: ALL_LANGUAGES,
    release: Release.ArakniSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sar"],
    talents: [Talent.Chaos],
  },
  {
    cards: 40,
    chapter: 2,
    classes: [Class.Ranger],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KFWFSGRBJS7BK87T8YF24FYC" },
    ],
    heroIdentifiers: ["azalea"],
    languages: ALL_LANGUAGES,
    release: Release.AzaleaSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["saz"],
    talents: [],
  },
  {
    cards: 40,
    chapter: 1,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KFWFTPVMBMZ9TT5GVT5QRRRM" },
    ],
    heroIdentifiers: ["bravo-flattering-showman"],
    languages: ALL_LANGUAGES,
    release: Release.BravoSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sbr"],
    talents: [],
  },
  {
    cards: 40,
    chapter: 1,
    classes: [Class.Mechanologist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KFWFW6EAT7VX44MKN8GCVQSM" },
    ],
    heroIdentifiers: ["dash"],
    languages: ALL_LANGUAGES,
    release: Release.DashSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sda"],
    talents: [],
  },
  {
    cards: 40,
    chapter: 2,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KFWFXK3QM2XEVA08D5Y1R3CF" },
    ],
    heroIdentifiers: ["dorinthea"],
    languages: ALL_LANGUAGES,
    release: Release.DorintheaSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sdo"],
    talents: [],
  },
  {
    cards: 40,
    chapter: 2,
    classes: [Class.Illusionist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KFWFYETE5DC1GK586XYXXFE6" },
    ],
    heroIdentifiers: ["enigma"],
    languages: ALL_LANGUAGES,
    release: Release.EnigmaSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sen"],
    talents: [Talent.Mystic],
  },
  {
    cards: 40,
    chapter: 2,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KFWD89C2CQFA1TA331EJ1Q2K" },
    ],
    heroIdentifiers: ["fai"],
    languages: ALL_LANGUAGES,
    release: Release.FaiSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sfa"],
    talents: [Talent.Draconic],
  },
  {
    cards: 40,
    chapter: 1,
    classes: [Class.Wizard],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KFWD9YWCRZ825T3AK8ZTG0G4" },
    ],
    heroIdentifiers: ["iyslander"],
    languages: ALL_LANGUAGES,
    release: Release.IyslanderSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["siy"],
    talents: [Talent.Elemental, Talent.Ice],
  },
  {
    cards: 40,
    chapter: 1,
    classes: [Class.Brute],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KFWFZ9Z5W17F0NHKQ44811Q0" },
    ],
    heroIdentifiers: ["kayo"],
    languages: ALL_LANGUAGES,
    release: Release.KayoSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["ska"],
    talents: [],
  },
  {
    cards: 40,
    chapter: 1,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KFWG05XQJT0NRVNGBZ4EJSSP" },
    ],
    heroIdentifiers: ["viserai"],
    languages: ALL_LANGUAGES,
    release: Release.ViseraiSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-02-13 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["svi"],
    talents: [],
  },
  {
    cards: 27,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KNHHE1MY39BC4PXYXMTJVT1M" },
    ],
    heroIdentifiers: ["hala-bladesaint-of-the-vow"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckOriginsHala,
    relatedReleases: [],
    releaseDate: "2026-04-17 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["aha"],
    talents: [],
  },
  {
    cards: 251,
    classes: [Class.Illusionist, Class.Runeblade, Class.Wizard],
    deckLinks: [],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "aurora-emissary-of-lightning",
      "aurora-legacy-of-tempest",
      "oscilio-forked-continuum",
      "oscilio-scion-of-the-third-age",
      "zyggy",
      "zyggy-starlight",
    ],
    languages: ALL_LANGUAGES,
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.OmensOfTheThirdAge,
    relatedReleases: [],
    releaseDate: "2026-06-05 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["omn"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KREWW7RJS0GZ2PCCD4BM47QY" },
    ],
    heroIdentifiers: ["zyggy-starlight"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckZyggy,
    relatedReleases: [],
    releaseDate: "2026-06-05 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["azs"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    chapter: 3,
    classes: [Class.Wizard],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KP7ZQMB111K73XT88YV5YN7C" },
    ],
    heroIdentifiers: ["blaze-firemind"],
    languages: ALL_LANGUAGES,
    release: Release.BlazeSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-06-05 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sbz"],
    talents: [],
  },
  {
    cards: 40,
    chapter: 3,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KP7ZQ311EMGC2S97KC79AEX0" },
    ],
    heroIdentifiers: ["boltyn"],
    languages: ALL_LANGUAGES,
    release: Release.BoltynSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-06-05 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sbl"],
    talents: [Talent.Light],
  },
  {
    cards: 40,
    chapter: 3,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KP7ZP4HXQTBZ2G37PMJ9W20N" },
    ],
    heroIdentifiers: ["briar"],
    languages: ALL_LANGUAGES,
    release: Release.BriarSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-06-05 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sba"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Lightning],
  },
  {
    cards: 40,
    chapter: 3,
    classes: [Class.Pirate, Class.Necromancer],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KP7ZNJYM2QVMNRS4DQKFZHQ4" },
    ],
    heroIdentifiers: ["gravy-bones"],
    languages: ALL_LANGUAGES,
    release: Release.GravyBonesSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-06-05 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sgb"],
    talents: [],
  },
  {
    cards: 40,
    chapter: 3,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KP7ZMZGHMACW17CRP12E7R45" },
    ],
    heroIdentifiers: ["lyath-goldmane"],
    languages: ALL_LANGUAGES,
    release: Release.LyathSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-06-05 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sly"],
    talents: [Talent.Reviled],
  },
  {
    cards: 156,
    classes: [Class.Warrior],
    deckLinks: [],
    heroIdentifiers: [
      "dorinthea",
      "dorinthea-quicksilver-prodigy",
      "hala",
      "hala-bladesaint-of-the-vow",
      "olympia",
    ],
    languages: ALL_LANGUAGES,
    release: Release.MasteryPackWarrior,
    relatedReleases: [],
    releaseDate: "2026-08-07 12:00",
    releaseType: ReleaseType.MasteryPack,
    setIdentifiers: ["mpw"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KP7ZJNFZZD8YNGP438FT8SFG" },
    ],
    heroIdentifiers: ["olympia-prized-fighter"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckOlympia,
    relatedReleases: [],
    releaseDate: "2026-08-07 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["aol"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KP7ZHK1HMQCVMFH6W62FTVZ2" },
    ],
    heroIdentifiers: ["dorinthea-quicksilver-prodigy"],
    languages: ALL_LANGUAGES,
    release: Release.DorintheaDemoDeck,
    relatedReleases: [],
    releaseDate: "2026-08-07 12:00",
    releaseType: ReleaseType.WelcomeDeck,
    setIdentifiers: ["ddd"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KYX5AKV8MSXP5310XSYF15DJ" },
    ],
    heroIdentifiers: ["prism-advent-of-thrones"],
    languages: ALL_LANGUAGES,
    release: Release.PrismSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-09-18 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sat"],
    talents: [Talent.Light],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01M1WWKBXCEF7RGFG9MM4PYRKB" },
    ],
    heroIdentifiers: ["viserai-between-worlds"],
    languages: ALL_LANGUAGES,
    release: Release.ViseraiBetweenWorldsSilverAgeDeck,
    relatedReleases: [],
    releaseDate: "2026-09-18 12:00",
    releaseType: ReleaseType.SilverAgeDeck,
    setIdentifiers: ["sbw"],
    talents: [Talent.Shadow],
  },
  {
    cards: 263,
    classes: [Class.Brute, Class.Necromancer, Class.Runeblade],
    deckLinks: [
      // { url: "https://fabrary.net/decks/01KP7ZHK1HMQCVMFH6W62FTVZ2" },
    ],
    draft: {
      picksPerPack: 14,
    },
    heroIdentifiers: [
      "baalghor-omen-of-the-end",
      "levia",
      "malice",
      "malice-domina-of-the-dead",
      "viserai-between-worlds",
      "viserai-the-forsaken",
    ],
    languages: ALL_LANGUAGES,
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.UsurpTheShadowThrone,
    relatedReleases: [],
    releaseDate: "2026-09-25 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["iar"],
    talents: [Talent.Shadow],
  },
  {
    cards: 30,
    classes: [Class.Necromancer],
    deckLinks: [
      { url: "https://fabrary.net/decks/01KXQF1YZHCHP2KAMDBS5WC5Q9" },
    ],
    heroIdentifiers: ["malice-domina-of-the-dead"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckMalice,
    relatedReleases: [],
    releaseDate: "2026-09-25 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["ama"],
    talents: [Talent.Shadow],
  },
  {
    cards: 107,
    classes: [Class.Thief, Class.Warrior],
    deckLinks: [],
    heroIdentifiers: ["killjoy-the-crooked-blade", "zane-broadly-beloved"],
    languages: [Language.English],
    release: Release.SmashPalaceChorusOfSteel,
    relatedReleases: [],
    releaseDate: "2026-10-30 12:00",
    releaseType: ReleaseType.BoxSet,
    talents: [Talent.Revered, Talent.Reviled],
    setIdentifiers: ["spw"],
  },
  {
    cards: 156,
    classes: [Class.Assassin],
    deckLinks: [],
    heroIdentifiers: [
      "arakni",
      "dr-mortimer",
      "dr-mortimer-blight-of-the-pits",
      "uzuri",
    ],
    languages: ALL_LANGUAGES,
    release: Release.MasteryPackAssassin,
    relatedReleases: [],
    releaseDate: "2026-11-13 12:00",
    releaseType: ReleaseType.MasteryPack,
    setIdentifiers: ["mpa"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Assassin],
    deckLinks: [
      // { url: "https://fabrary.net/decks/01M01B0MCJRZHMDRFZNBCT1B1J" },
    ],
    heroIdentifiers: ["dr-mortimer-blight-of-the-pits"],
    languages: ALL_LANGUAGES,
    release: Release.ArmoryDeckDrMortimer,
    relatedReleases: [],
    releaseDate: "2026-11-13 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["amo"],
    talents: [],
  },
  {
    classes: [],
    deckLinks: [],
    heroIdentifiers: [],
    languages: [Language.English],
    release: Release.GEM,
    relatedReleases: [],
    releaseType: ReleaseType.Promo,
    setIdentifiers: ["gem"],
    talents: [],
  },
  {
    classes: [],
    deckLinks: [],
    heroIdentifiers: [],
    languages: [Language.English],
    release: Release.Promos,
    relatedReleases: [],
    releaseType: ReleaseType.Promo,
    setIdentifiers: [
      "anq",
      "con",
      "fab",
      "her",
      "jdg",
      "lgs",
      "lss",
      "oxo",
      "xxx",
      "win",
    ],
    talents: [],
  },
  {
    classes: [],
    deckLinks: [],
    heroIdentifiers: [],
    languages: [Language.English],
    release: Release.TournamentPack,
    relatedReleases: [],
    releaseType: ReleaseType.Promo,
    setIdentifiers: ["tnp"],
    talents: [],
  },
];

const getReleaseBySetIdentifier = (): Map<string, Release> => {
  const releaseBySetIdentifier = new Map<string, Release>();

  for (const { release, setIdentifiers } of releases) {
    for (const setIdentifier of setIdentifiers) {
      const releaseWithSameIdentifier =
        releaseBySetIdentifier.get(setIdentifier);

      if (releaseWithSameIdentifier) {
        throw new Error(
          `${releaseWithSameIdentifier} and ${release} both carry the set identifier "${setIdentifier}"`,
        );
      } else {
        releaseBySetIdentifier.set(setIdentifier, release);
      }
    }
  }

  return releaseBySetIdentifier;
};

// Keyed by lowercase identifier, as source rows are read.
export const releaseBySetIdentifier = getReleaseBySetIdentifier();

// Keyed by name as a string, since source data names a release in raw text.
export const releaseInfoByRelease = new Map<string, ReleaseInfo>(
  releases.map((releaseInfo) => [releaseInfo.release, releaseInfo]),
);

/**
 * The catalogue index resolves a set filter's value against release names as
 * a filter reads them, so two names reading alike would leave that value
 * naming either release.
 */
export const assertReleaseNamesAreUnique = (): void => {
  const releaseByFilterName = new Map<string, Release>();

  for (const { release } of releases) {
    const filterName = getNormalizedFilterValue(release);
    const releaseWithSameName = releaseByFilterName.get(filterName);

    if (releaseWithSameName) {
      throw new Error(
        `${releaseWithSameName} and ${release} are one name as a filter reads it, so a set filter naming it could reach either`,
      );
    } else {
      releaseByFilterName.set(filterName, release);
    }
  }
};
