import { Class, Hero, Rarity, Release, Talent } from "./interfaces";

export enum Language {
  English = "English",
  French = "Français",
  German = "Deutsch",
  Italian = "Italiano",
  Japanese = "日本語",
  Spanish = "Español",
}

const ALL_LANGUAGES = [
  Language.English,
  Language.French,
  Language.German,
  Language.Italian,
  Language.Japanese,
  Language.Spanish,
];

export enum ReleaseType {
  ArmoryDeck = "Armory Deck",
  BlitzDeck = "Blitz Deck",
  ClassicBattles = "Classic Battles",
  ExpansionBooster = "Expansion Booster",
  FirstStrike = "1st Strike",
  HistoryPack = "History Pack",
  MasteryPack = "Mastery Pack",
  RoundTheTable = "Round the Table",
  StandaloneBooster = "Standalone Booster",
  WelcomeDeck = "Welcome Deck",
}

const BOOSTER_RELEASE_TYPES = [
  ReleaseType.ExpansionBooster,
  ReleaseType.StandaloneBooster,
];
export const getIsBooster = (releaseType: ReleaseType) =>
  BOOSTER_RELEASE_TYPES.includes(releaseType);

export const getIsReprint = (releaseType: ReleaseType) =>
  releaseType === ReleaseType.HistoryPack;

export const getIsDraftable = (releaseType: ReleaseType) =>
  releaseType === ReleaseType.StandaloneBooster;

const PRECONSTRUCTED_RELEASE_TYPES = [
  ReleaseType.ArmoryDeck,
  ReleaseType.BlitzDeck,
  ReleaseType.ClassicBattles,
  ReleaseType.FirstStrike,
  ReleaseType.RoundTheTable,
  ReleaseType.WelcomeDeck,
];
export const getIsPreconstructed = (releaseType: ReleaseType) =>
  PRECONSTRUCTED_RELEASE_TYPES.includes(releaseType);

export const coreSetIdentifiers: { [key: string]: Release } = {
  wtr: Release.WelcomeToRathe,
  arc: Release.ArcaneRising,
  mon: Release.Monarch,
  ele: Release.TalesOfAria,
  upr: Release.Uprising,
  out: Release.Outsiders,
  evo: Release.BrightLights,
  hvy: Release.HeavyHitters,
  mst: Release.PartTheMistveil,
  ros: Release.Rosetta,
};

export const supplementalSetIdentifiers: { [key: string]: Release } = {
  cru: Release.CrucibleOfWar,
  evr: Release.Everfest,
  "1hp": Release.HistoryPack1,
  hp1: Release.HistoryPack1,
  dyn: Release.Dynasty,
  dtd: Release.DuskTillDawn,
};

export const promoSetIdentifiers = [
  "fab",
  "her",
  "jdg",
  "lgs",
  "lss",
  "oxo",
  "xxx",
  "win",
];

interface DeckLink {
  name?: string;
  url: string;
}

export interface ReleaseInfo {
  cards: number;
  classes: Class[];
  deckLinks: DeckLink[];
  heroes: Hero[];
  heroOverrides?: {
    [key: string]: Hero;
  };
  languages: Language[];
  raritiesExcludedInLimited?: Rarity[];
  relatedReleases: Release[];
  release: Release;
  releaseDate: string;
  releaseType: ReleaseType;
  setIdentifiers: string[];
  talents: Talent[];
  url?: string;
}

export const releases: ReleaseInfo[] = [
  {
    cards: 30,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GJG7Z4WGWSZ95FY74KX4M557" },
    ],
    heroes: [Hero.Ira],
    languages: ALL_LANGUAGES,
    release: Release.IraWelcomeDeck,
    relatedReleases: [],
    releaseDate: "2019-08-31 12:00",
    releaseType: ReleaseType.WelcomeDeck,
    setIdentifiers: ["ira"],
    talents: [],
  },
  {
    cards: 226,
    classes: [Class.Brute, Class.Guardian, Class.Ninja, Class.Warrior],
    deckLinks: [],
    heroes: [Hero.Bravo, Hero.Dorinthea, Hero.Katsu, Hero.Rhinar],
    languages: [Language.English],
    release: Release.WelcomeToRathe,
    relatedReleases: [],
    releaseDate: "2019-10-11 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["wtr"],
    talents: [],
  },
  {
    cards: 219,
    classes: [Class.Mechanologist, Class.Ranger, Class.Runeblade, Class.Wizard],
    deckLinks: [],
    heroes: [Hero.Azalea, Hero.Dash, Hero.Kano, Hero.Viserai],
    languages: [Language.English],
    release: Release.ArcaneRising,
    relatedReleases: [],
    releaseDate: "2020-03-27 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["arc"],
    talents: [],
  },
  {
    cards: 194,
    classes: [
      Class.Brute,
      Class.Guardian,
      Class.Mechanologist,
      Class.Merchant,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    deckLinks: [],
    heroes: [
      Hero.Benji,
      Hero.DataDoll,
      Hero.Ira,
      Hero.Kassai,
      Hero.Kavdaen,
      Hero.Kayo,
      Hero.Shiyana,
    ],
    languages: [Language.English],
    release: Release.CrucibleOfWar,
    relatedReleases: [],
    releaseDate: "2020-08-28 12:00",
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["cru"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7FD2B3YQAMR8NJ4B3M58H96" },
    ],
    heroes: [Hero.Boltyn],
    languages: [Language.English],
    release: Release.BoltynBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-05-07 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["bol"],
    talents: [Talent.Light],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7FDVRZP35DFWBRK64AG5TKQ" },
    ],
    heroes: [Hero.Chane],
    languages: [Language.English],
    release: Release.ChaneBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-05-07 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["chn"],
    talents: [Talent.Shadow],
  },
  {
    cards: 40,
    classes: [Class.Brute],
    languages: [Language.English],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7B1T1D1M2DAM61K876VJBDK" },
    ],
    heroes: [Hero.Levia],
    release: Release.LeviaBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-05-07 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["lev"],
    talents: [Talent.Shadow],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7FCP2N7N0MNHWAH6JTP0KFN" },
    ],
    heroes: [Hero.Prism],
    languages: [Language.English],
    relatedReleases: [],
    releaseDate: "2021-05-07 12:00",
    release: Release.PrismBlitzDeck,
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["psm"],
    talents: [Talent.Light],
  },
  {
    cards: 307,
    classes: [Class.Brute, Class.Illusionist, Class.Runeblade, Class.Warrior],
    deckLinks: [],
    heroes: [Hero.Boltyn, Hero.Chane, Hero.Levia, Hero.Prism],
    languages: [Language.English],
    release: Release.Monarch,
    relatedReleases: [
      Release.BoltynBlitzDeck,
      Release.ChaneBlitzDeck,
      Release.LeviaBlitzDeck,
      Release.PrismBlitzDeck,
    ],
    releaseDate: "2021-05-07 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["mon"],
    talents: [Talent.Light, Talent.Shadow],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7K4D304QQCZZSBT7ABCX4XC" },
    ],
    heroes: [Hero.Briar],
    languages: [Language.English],
    release: Release.BriarBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-11-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    talents: [Talent.Elemental, Talent.Earth, Talent.Lightning],
    setIdentifiers: ["bri"],
  },
  {
    cards: 40,
    classes: [Class.Ranger],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7K3WGPVKVDXG2J013GXSXNP" },
    ],
    heroes: [Hero.Lexi],
    languages: [Language.English],
    release: Release.LexiBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-11-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["lxi"],
    talents: [Talent.Elemental, Talent.Ice, Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G7K464J7VS0K7HKW5E395TBK" },
    ],
    heroes: [Hero.Oldhim],
    languages: [Language.English],
    release: Release.OldhimBlitzDeck,
    relatedReleases: [],
    releaseDate: "2021-11-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["old"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice],
  },
  {
    cards: 238,
    classes: [Class.Guardian, Class.Ranger, Class.Runeblade],
    deckLinks: [],
    heroes: [Hero.Briar, Hero.Lexi, Hero.Oldhim],
    languages: [Language.English],
    release: Release.TalesOfAria,
    relatedReleases: [
      Release.BriarBlitzDeck,
      Release.LexiBlitzDeck,
      Release.OldhimBlitzDeck,
    ],
    releaseDate: "2021-09-24 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["ele"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice, Talent.Lightning],
  },
  {
    cards: 198,
    classes: [
      Class.Brute,
      Class.Guardian,
      Class.Illusionist,
      Class.Mechanologist,
      Class.Merchant,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    deckLinks: [],
    heroes: [Hero.Genis, Hero.Valda],
    languages: [Language.English],
    release: Release.Everfest,
    relatedReleases: [],
    releaseDate: "2022-02-04 12:00",
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["evr"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice, Talent.Lightning],
  },
  {
    cards: 423,
    classes: [
      Class.Brute,
      Class.Guardian,
      Class.Mechanologist,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    deckLinks: [],
    heroes: [
      Hero.Azalea,
      Hero.Benji,
      Hero.Bravo,
      Hero.Dash,
      Hero.DataDoll,
      Hero.Dorinthea,
      Hero.Ira,
      Hero.Kassai,
      Hero.Katsu,
      Hero.Kayo,
      Hero.Rhinar,
      Hero.Viserai,
      Hero.Kano,
    ],
    languages: [Language.English],
    release: Release.HistoryPack1,
    relatedReleases: [],
    releaseDate: "2022-05-06 12:00",
    releaseType: ReleaseType.HistoryPack,
    setIdentifiers: ["1hp", "hp1"],
    talents: [],
  },
  {
    cards: 80,
    classes: [Class.Brute, Class.Warrior],
    deckLinks: [
      {
        name: "Dorinthea",
        url: "https://fabrary.net/decks/01GA4WTNSD12YTQB4FY8EYYNG5",
      },
      {
        name: "Rhinar",
        url: "https://fabrary.net/decks/01GA4WZKX9VEWKKPX7Y7H3MG1F",
      },
    ],
    heroes: [Hero.Dorinthea, Hero.Rhinar],
    languages: [Language.English],
    release: Release.ClassicBattlesRhinarDorinthea,
    relatedReleases: [],
    releaseDate: "2022-05-27 12:00",
    releaseType: ReleaseType.ClassicBattles,
    setIdentifiers: ["dvr", "rvd"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G76H1R1ERRBRKS7RVCQAB8RX" },
    ],
    heroes: [Hero.Dromai],
    languages: [Language.English],
    relatedReleases: [],
    releaseDate: "2022-06-24 12:00",
    release: Release.DromaiBlitzDeck,
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["dro"],
    talents: [Talent.Draconic],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01G76H7RG7GN5ZA10F3BJBH740" },
    ],
    heroes: [Hero.Fai],
    languages: [Language.English],
    release: Release.FaiBlitzDeck,
    relatedReleases: [],
    releaseDate: "2022-06-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["fai"],
    talents: [Talent.Draconic],
  },
  {
    cards: 226,
    classes: [Class.Illusionist, Class.Ninja, Class.Wizard],
    deckLinks: [],
    heroes: [Hero.Dromai, Hero.Fai, Hero.Iyslander],
    languages: [Language.English],
    release: Release.Uprising,
    relatedReleases: [Release.DromaiBlitzDeck, Release.FaiBlitzDeck],
    releaseDate: "2022-06-24 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["upr"],
    talents: [Talent.Draconic, Talent.Elemental, Talent.Ice],
  },
  {
    cards: 247,
    classes: [
      Class.Assassin,
      Class.Brute,
      Class.Guardian,
      Class.Illusionist,
      Class.Mechanologist,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    deckLinks: [],
    heroes: [Hero.Arakni, Hero.Emperor, Hero.Yoji],
    languages: [Language.English],
    release: Release.Dynasty,
    relatedReleases: [],
    releaseDate: "2022-11-11 12:00",
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["dyn"],
    talents: [Talent.Royal],
  },
  // {
  //   cards: 536,
  //   classes: [
  //     Class.Brute,
  //     Class.Guardian,
  //     Class.Illusionist,
  //     Class.Mechanologist,
  //     Class.Ninja,
  //     Class.Ranger,
  //     Class.Runeblade,
  //     Class.Warrior,
  //     Class.Wizard,
  //   ],
  //   deckLinks: [],
  //   heroes: [
  //     Hero.Boltyn,
  //     Hero.Briar,
  //     Hero.Chane,
  //     Hero.Levia,
  //     Hero.Lexi,
  //     Hero.Oldhim,
  //     Hero.Prism,
  //   ],
  //   languages: [
  //     Language.French,
  //     Language.German,
  //     Language.Italian,
  //     Language.Spanish,
  //   ],
  //   release: "History Pack 2: Black Label" as Release,
  //   relatedReleases: [],
  //   releaseDate: "2023-02-24 12:00",
  //   releaseType: ReleaseType.HistoryPack,
  //   setIdentifiers: ["hp2"],
  //   talents: [
  //     Talent.Elemental,
  //     Talent.Earth,
  //     Talent.Ice,
  //     Talent.Lightning,
  //     Talent.Light,
  //     Talent.Shadow,
  //   ],
  // },
  {
    cards: 40,
    classes: [Class.Assassin],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW25PNWBW2FPDHRNTPSET0GT" },
    ],
    heroes: [Hero.Arakni],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.ArakniBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ara"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ranger],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW26RNH1Q1J0S1VFXPN609S2" },
    ],
    heroes: [Hero.Azalea],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.AzaleaBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["azl"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW28622XSVAK7H9RXZVAVKM0" },
    ],
    heroes: [Hero.Benji],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.BenjiBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ben"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW28TF5FXFKJ5CGRNXB84CG6" },
    ],
    heroes: [Hero.Katsu],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.KatsuBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["kat"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ranger],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW29DPNZ3XVBJQHHFQHHHDGN" },
    ],
    heroes: [Hero.Riptide],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.RiptideBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["rip"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    deckLinks: [
      { url: "https://fabrary.net/decks/01GW2945GHPH2YSX3FTS7HCBT1" },
    ],
    heroes: [Hero.Uzuri],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.UzuriBlitzDeck,
    relatedReleases: [],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["uzu"],
    talents: [],
  },
  {
    cards: 239,
    classes: [Class.Assassin, Class.Ranger, Class.Ninja],
    deckLinks: [],
    heroes: [
      Hero.Arakni,
      Hero.Azalea,
      Hero.Benji,
      Hero.Katsu,
      Hero.Riptide,
      Hero.Uzuri,
    ],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.Outsiders,
    relatedReleases: [
      Release.ArakniBlitzDeck,
      Release.AzaleaBlitzDeck,
      Release.BenjiBlitzDeck,
      Release.KatsuBlitzDeck,
      Release.RiptideBlitzDeck,
      Release.UzuriBlitzDeck,
    ],
    releaseDate: "2023-03-24 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["out"],
    talents: [],
  },
  {
    cards: 236,
    classes: [Class.Illusionist, Class.Runeblade, Class.Warrior, Class.Brute],
    deckLinks: [],
    heroes: [Hero.Prism, Hero.Vynnset, Hero.Boltyn, Hero.Levia],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.DuskTillDawn,
    relatedReleases: [],
    releaseDate: "2023-07-14 12:00",
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["dtd"],
    talents: [Talent.Light, Talent.Shadow],
  },
  {
    cards: 107,
    classes: [Class.Mechanologist, Class.Bard, Class.Guardian, Class.Ninja],
    deckLinks: [
      {
        name: "Brevant",
        url: "https://fabrary.net/decks/01HAXKPFH7ZHPDEJZH967VNRW6",
      },
      {
        name: "Ira",
        url: "https://fabrary.net/decks/01HAXKZMTRN4FR7CFTQA11A70N",
      },
      {
        name: "Melody",
        url: "https://fabrary.net/decks/01HAXKSFPXGCEH99PDZJ32V4N9",
      },
      {
        name: "Teklovossen",
        url: "https://fabrary.net/decks/01HAXKZMTRN4FR7CFTQA11A70N",
      },
    ],
    heroes: [Hero.Teklovossen, Hero.Melody, Hero.Brevant, Hero.Ira],
    languages: [Language.English],
    release: Release.RoundTheTable,
    relatedReleases: [],
    releaseDate: "2023-09-29 12:00",
    releaseType: ReleaseType.RoundTheTable,
    talents: [],
    setIdentifiers: ["tcc"],
  },
  {
    cards: 251,
    classes: [Class.Mechanologist],
    deckLinks: [],
    heroes: [Hero.Dash, Hero.Maxx, Hero.Teklovossen],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.BrightLights,
    relatedReleases: [],
    releaseDate: "2023-10-06 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["evo"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3J1X1NQ9TB9RTVWV42JG46" },
    ],
    heroes: [Hero.Betsy],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.BetsyBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["bet"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3SHBEQBRECYK6ZN1CHRADR" },
    ],
    heroes: [Hero.Kassai],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.KassaiBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ksi"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Brute],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3HK89NA910SK3FQV84H46Z" },
    ],
    heroes: [Hero.Kayo],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.KayoBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["kyo"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3GP5ZJ1NRC0XBYNE45XQE8" },
    ],
    heroes: [Hero.Olympia],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.OlympiaBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ola"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Brute],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3Q4GBDMEFSX98HEN9ET308" },
    ],
    heroes: [Hero.Rhinar],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.RhinarBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["rhi"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HN3K8ZV7KBRRJKPHW4B13J1K" },
    ],
    heroes: [Hero.Victor],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.VictorBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["vic"],
    talents: [],
  },
  {
    cards: 255,
    classes: [Class.Brute, Class.Guardian, Class.Warrior],
    deckLinks: [],
    heroes: [
      Hero.Kassai,
      Hero.Betsy,
      Hero.Kayo,
      Hero.Olympia,
      Hero.Rhinar,
      Hero.Victor,
    ],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.HeavyHitters,
    relatedReleases: [
      Release.BetsyBlitzDeck,
      Release.KassaiBlitzDeck,
      Release.KayoBlitzDeck,
      Release.OlympiaBlitzDeck,
      Release.RhinarBlitzDeck,
      Release.VictorBlitzDeck,
    ],
    releaseDate: "2024-02-02 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["hvy"],
    talents: [],
  },
  {
    cards: 66,
    classes: [Class.Brute],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HWNCK2BYPVKK6701052YYXMZ" },
    ],
    heroes: [Hero.Kayo],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckKayo,
    relatedReleases: [],
    releaseDate: "2024-05-03 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["ako"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HX5Z23X2PRQCJ100FP4CAZGK" },
    ],
    heroes: [Hero.Enigma],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.EnigmaBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-05-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["eng"],
    talents: [Talent.Mystic],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HX5Z4BD3TRMS3CP1ME4ZP3T6" },
    ],
    heroes: [Hero.Nuu],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.NuuBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-05-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["nuu"],
    talents: [Talent.Mystic],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    deckLinks: [
      { url: "https://fabrary.net/decks/01HX5Z395FD35CM24QCJQKJER1" },
    ],
    heroes: [Hero.Zen],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.ZenBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-05-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["zen"],
    talents: [Talent.Mystic],
  },
  {
    cards: 239,
    classes: [Class.Assassin, Class.Illusionist, Class.Ninja],
    deckLinks: [],
    heroes: [Hero.Enigma, Hero.Nuu, Hero.Zen],
    languages: ALL_LANGUAGES,
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.PartTheMistveil,
    relatedReleases: [
      Release.EnigmaBlitzDeck,
      Release.NuuBlitzDeck,
      Release.ZenBlitzDeck,
    ],
    releaseDate: "2024-05-31 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["mst"],
    talents: [Talent.Mystic],
  },
  {
    cards: 66,
    classes: [Class.Warrior],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J202NH0RG8S0V8WXH1FWB2AH" },
    ],
    heroes: [Hero.Boltyn],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckBoltyn,
    relatedReleases: [],
    releaseDate: "2024-07-12 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["asb"],
    talents: [Talent.Light],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J45SYSM2ZERW6CWY283ZAT1S" },
    ],
    heroes: [Hero.Aurora],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.FirstStrikeAurora,
    relatedReleases: [],
    releaseDate: "2024-08-01 12:00",
    releaseType: ReleaseType.FirstStrike,
    setIdentifiers: ["aur"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J45SWXNDV5XD8PTBACAV8NZ1" },
    ],
    heroes: [Hero.Terra],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.FirstStrikeTerra,
    relatedReleases: [],
    releaseDate: "2024-08-01 12:00",
    releaseType: ReleaseType.FirstStrike,
    setIdentifiers: ["ter"],
    talents: [Talent.Earth],
  },
  {
    cards: 66,
    classes: [Class.Ranger],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J3GKKSTM773CW7BG3RRJ5FJH" },
    ],
    heroes: [Hero.Azalea],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckAzalea,
    relatedReleases: [],
    releaseDate: "2024-08-02 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["aaz"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J68KF1TFNN62TC0G7M993FTY" },
    ],
    heroes: [Hero.Aurora],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.AuroraBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-09-20 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["aua"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J68KFRMJFKRQYJJ7THG1GMTB" },
    ],
    heroes: [Hero.Florian],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.FlorianBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-09-20 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["flr"],
    talents: [Talent.Earth],
  },
  {
    cards: 40,
    classes: [Class.Wizard],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J68KGA3JVKFHEXGKYW0441CY" },
    ],
    heroes: [Hero.Oscilio],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.OscilioBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-09-20 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["osc"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Wizard],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J68KGT3XD3HMVVRFT174QNMF" },
    ],
    heroes: [Hero.Verdance],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.VerdanceBlitzDeck,
    relatedReleases: [],
    releaseDate: "2024-09-20 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ver"],
    talents: [Talent.Earth],
  },
  {
    cards: 258,
    classes: [Class.Runeblade, Class.Wizard],
    deckLinks: [],
    heroes: [Hero.Aurora, Hero.Florian, Hero.Oscilio, Hero.Verdance],
    languages: ALL_LANGUAGES,
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.Rosetta,
    relatedReleases: [
      Release.AuroraBlitzDeck,
      Release.FlorianBlitzDeck,
      Release.OscilioBlitzDeck,
      Release.VerdanceBlitzDeck,
    ],
    releaseDate: "2024-09-20 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["ros"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Lightning],
  },
  {
    cards: 66,
    classes: [Class.Mechanologist],
    deckLinks: [
      { url: "https://fabrary.net/decks/01J9822H5PANJAFQVMC4TPK4Z1" },
    ],
    heroes: [Hero.Dash],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckDash,
    relatedReleases: [],
    releaseDate: "2024-10-18 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["aio"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Guardian],
    deckLinks: [
      { url: "https://fabrary.net/decks/01JCPPENK52DTRBJZMWQF8S0X2" },
    ],
    heroes: [Hero.Jarl],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckOriginsJarl,
    relatedReleases: [],
    releaseDate: "2024-11-29 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["ajv"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    deckLinks: [],
    heroes: [Hero.Arakni],
    languages: ALL_LANGUAGES,
    release: Release.ArakniBlitzDeckARK,
    relatedReleases: [],
    releaseDate: "2025-01-31 12:00",
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ark"],
    talents: [Talent.Chaos],
  },
  {
    cards: 265,
    classes: [Class.Assassin, Class.Ninja, Class.Warrior],
    deckLinks: [],
    heroes: [Hero.Arakni, Hero.Cindra, Hero.Fang],
    heroOverrides: {
      [Hero.Arakni]: Hero.Crackni,
    },
    languages: ALL_LANGUAGES,
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.TheHunted,
    relatedReleases: [],
    releaseDate: "2025-01-31 12:00",
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["hnt"],
    talents: [Talent.Chaos, Talent.Draconic, Talent.Royal],
    url: "https://fabtcg.com/en/articles/hnt/",
  },
  {
    cards: 30,
    classes: [Class.Runeblade],
    deckLinks: [
      // { url: "https://fabrary.net/decks/01JCPPENK52DTRBJZMWQF8S0X2" },
    ],
    heroes: [Hero.Aurora],
    languages: [Language.English, Language.French, Language.Japanese],
    release: Release.ArmoryDeckAurora,
    relatedReleases: [],
    releaseDate: "2025-03-14 12:00",
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["ast"],
    talents: [Talent.Elemental, Talent.Lightning],
  },
];

export const fullSetIdentifiers: { [key: string]: Release } = {
  wtr: Release.WelcomeToRathe,
  arc: Release.ArcaneRising,
  cru: Release.CrucibleOfWar,
  mon: Release.Monarch,
  ele: Release.TalesOfAria,
  evr: Release.Everfest,
  "1hp": Release.HistoryPack1,
  hp1: Release.HistoryPack1,
  upr: Release.Uprising,
  dyn: Release.Dynasty,
  out: Release.Outsiders,
  dtd: Release.DuskTillDawn,
  evo: Release.BrightLights,
  hvy: Release.HeavyHitters,
  mst: Release.PartTheMistveil,
  ros: Release.Rosetta,
  hnt: Release.TheHunted,
};

export const setIdentifierToSetMappings: { [key: string]: Release } = {
  ...fullSetIdentifiers,

  // Armory decks
  aaz: Release.ArmoryDeckAzalea,
  asb: Release.ArmoryDeckBoltyn,
  aio: Release.ArmoryDeckDash,
  ako: Release.ArmoryDeckKayo,
  ajv: Release.ArmoryDeckOriginsJarl,
  ast: Release.ArmoryDeckAurora,

  // Blitz decks
  ara: Release.ArakniBlitzDeck,
  ark: Release.ArakniBlitzDeckARK,
  aua: Release.AuroraBlitzDeck,
  azl: Release.AzaleaBlitzDeck,
  ben: Release.BenjiBlitzDeck,
  bet: Release.BetsyBlitzDeck,
  bol: Release.BoltynBlitzDeck,
  bri: Release.BriarBlitzDeck,
  chn: Release.ChaneBlitzDeck,
  dro: Release.DromaiBlitzDeck,
  eng: Release.EnigmaBlitzDeck,
  fai: Release.FaiBlitzDeck,
  flr: Release.FlorianBlitzDeck,
  kat: Release.KatsuBlitzDeck,
  ksi: Release.KassaiBlitzDeck,
  kyo: Release.KayoBlitzDeck,
  lev: Release.LeviaBlitzDeck,
  lxi: Release.LexiBlitzDeck,
  nuu: Release.NuuBlitzDeck,
  old: Release.OldhimBlitzDeck,
  ola: Release.OlympiaBlitzDeck,
  osc: Release.OscilioBlitzDeck,
  psm: Release.PrismBlitzDeck,
  rip: Release.RiptideBlitzDeck,
  rhi: Release.RhinarBlitzDeck,
  uzu: Release.UzuriBlitzDeck,
  ver: Release.VerdanceBlitzDeck,
  vic: Release.VictorBlitzDeck,
  zen: Release.ZenBlitzDeck,

  // 1st strike decks
  aur: Release.FirstStrikeAurora,
  ter: Release.FirstStrikeTerra,

  // Starter decks
  dvr: Release.ClassicBattlesRhinarDorinthea,
  rvd: Release.ClassicBattlesRhinarDorinthea,
  ira: Release.IraWelcomeDeck,

  // Other decks
  tcc: Release.RoundTheTable,

  // Hero decks
  bvo: Release.BravoHeroDeck,
  tea: Release.DorintheaHeroDeck,
  ksu: Release.KatsuHeroDeck,
  rnr: Release.RhinarHeroDeck,

  // GEM packs
  gem: Release.GEM,

  // Promos
  fab: Release.Promos,
  her: Release.Promos,
  jdg: Release.Promos,
  lgs: Release.Promos,
  lss: Release.Promos,
  oxo: Release.Promos,
  xxx: Release.Promos,
  win: Release.Promos,
};

let tempSetToSetIdentifierMappings: { [key: string]: string[] } = {};
for (const [setIdentifier, set] of Object.entries(setIdentifierToSetMappings)) {
  const entry = tempSetToSetIdentifierMappings[set];
  if (entry) {
    entry.push(setIdentifier);
  } else {
    tempSetToSetIdentifierMappings[set] = [setIdentifier];
  }
}

export const setToSetIdentifierMappings = tempSetToSetIdentifierMappings;
