import { Class, Format, Hero, Rarity, Release, Talent } from "./interfaces";

export enum Language {
  English = "English",
  French = "Français",
  German = "Deutsch",
  Italian = "Italiano",
  Japanese = "日本語",
  Spanish = "Español",
}

const ALL_LANGUAGES = [
  Language.English,
  Language.French,
  Language.German,
  Language.Italian,
  Language.Japanese,
  Language.Spanish,
];

export enum ReleaseType {
  ArmoryDeck = "Armory Deck",
  BlitzDeck = "Blitz Deck",
  ClassicBattles = "Classic Battles",
  ExpansionBooster = "Expansion Booster",
  FirstStrike = "1st Strike",
  HistoryPack = "History Pack",
  MasteryPack = "Mastery Pack",
  RoundTheTable = "Round the Table",
  StandaloneBooster = "Standalone Booster",
  WelcomeDeck = "Welcome Deck",
}

const BOOSTER_RELEASE_TYPES = [
  ReleaseType.ExpansionBooster,
  ReleaseType.StandaloneBooster,
];
export const getIsBooster = (releaseType: ReleaseType) =>
  BOOSTER_RELEASE_TYPES.includes(releaseType);

export const getIsReprint = (releaseType: ReleaseType) =>
  releaseType === ReleaseType.HistoryPack;

export const getIsDraftable = (releaseType: ReleaseType) =>
  releaseType === ReleaseType.StandaloneBooster;

const PRECONSTRUCTED_RELEASE_TYPES = [
  ReleaseType.ArmoryDeck,
  ReleaseType.BlitzDeck,
  ReleaseType.ClassicBattles,
  ReleaseType.FirstStrike,
  ReleaseType.WelcomeDeck,
];
export const getIsPreconstructed = (releaseType: ReleaseType) =>
  PRECONSTRUCTED_RELEASE_TYPES.includes(releaseType);

export const coreSetIdentifiers: { [key: string]: Release } = {
  wtr: Release.WelcomeToRathe,
  arc: Release.ArcaneRising,
  mon: Release.Monarch,
  ele: Release.TalesOfAria,
  upr: Release.Uprising,
  out: Release.Outsiders,
  evo: Release.BrightLights,
  hvy: Release.HeavyHitters,
  mst: Release.PartTheMistveil,
  ros: Release.Rosetta,
};

export const supplementalSetIdentifiers: { [key: string]: Release } = {
  cru: Release.CrucibleOfWar,
  evr: Release.Everfest,
  "1hp": Release.HistoryPack1,
  hp1: Release.HistoryPack1,
  dyn: Release.Dynasty,
  dtd: Release.DuskTillDawn,
};

export const promoSetIdentifiers = [
  "fab",
  "her",
  "jdg",
  "lgs",
  "lss",
  "oxo",
  "xxx",
  "win",
];

export interface ReleaseInfo {
  cards: number;
  classes: Class[];
  format?: Format;
  heroes: Hero[];
  languages: Language[];
  raritiesExcludedInLimited?: Rarity[];
  release: Release;
  releaseDate: Date;
  releaseType: ReleaseType;
  setIdentifiers: string[];
  talents: Talent[];
}

export const releases: ReleaseInfo[] = [
  {
    cards: 30,
    classes: [Class.Ninja],
    heroes: [Hero.Ira],
    languages: ALL_LANGUAGES,
    release: Release.IraWelcomeDeck,
    releaseDate: new Date("2019-08-31T00:00:00.000Z"),
    releaseType: ReleaseType.WelcomeDeck,
    setIdentifiers: ["ira"],
    talents: [],
  },
  {
    cards: 226,
    classes: [Class.Brute, Class.Guardian, Class.Ninja, Class.Warrior],
    heroes: [Hero.Bravo, Hero.Dorinthea, Hero.Katsu, Hero.Rhinar],
    languages: [Language.English],
    release: Release.WelcomeToRathe,
    releaseDate: new Date("2019-10-11T00:00:00.000Z"),
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["wtr"],
    talents: [],
  },
  {
    cards: 219,
    classes: [Class.Mechanologist, Class.Ranger, Class.Runeblade, Class.Wizard],
    heroes: [Hero.Azalea, Hero.Dash, Hero.Kano, Hero.Viserai],
    languages: [Language.English],
    release: Release.ArcaneRising,
    releaseDate: new Date("2020-03-27T00:00:00.000Z"),
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["arc"],
    talents: [],
  },
  {
    cards: 194,
    classes: [
      Class.Brute,
      Class.Guardian,
      Class.Mechanologist,
      Class.Merchant,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    heroes: [
      Hero.Benji,
      Hero.DataDoll,
      Hero.Ira,
      Hero.Kassai,
      Hero.Kavdaen,
      Hero.Kayo,
      Hero.Shiyana,
    ],
    languages: [Language.English],
    release: Release.CrucibleOfWar,
    releaseDate: new Date("2020-08-28T00:00:00.000Z"),
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["cru"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Warrior],
    heroes: [Hero.Boltyn],
    languages: [Language.English],
    release: Release.BoltynBlitzDeck,
    releaseDate: new Date("2021-05-07T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["bol"],
    talents: [Talent.Light],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    heroes: [Hero.Chane],
    languages: [Language.English],
    release: Release.ChaneBlitzDeck,
    releaseDate: new Date("2021-05-07T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["chn"],
    talents: [Talent.Shadow],
  },
  {
    cards: 40,
    classes: [Class.Brute],
    languages: [Language.English],
    heroes: [Hero.Levia],
    release: Release.LeviaBlitzDeck,
    releaseDate: new Date("2021-05-07T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["lev"],
    talents: [Talent.Shadow],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    heroes: [Hero.Prism],
    languages: [Language.English],
    releaseDate: new Date("2021-05-07T00:00:00.000Z"),
    release: Release.PrismBlitzDeck,
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["psm"],
    talents: [Talent.Light],
  },
  {
    cards: 307,
    classes: [Class.Brute, Class.Illusionist, Class.Runeblade, Class.Warrior],
    heroes: [Hero.Boltyn, Hero.Chane, Hero.Levia, Hero.Prism],
    languages: [Language.English],
    release: Release.Monarch,
    releaseDate: new Date("2021-05-07T00:00:00.000Z"),
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["mon"],
    talents: [Talent.Light, Talent.Shadow],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    heroes: [Hero.Briar],
    languages: [Language.English],
    release: Release.BriarBlitzDeck,
    releaseDate: new Date("2021-11-24T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    talents: [Talent.Elemental, Talent.Earth, Talent.Lightning],
    setIdentifiers: ["bri"],
  },
  {
    cards: 40,
    classes: [Class.Ranger],
    heroes: [Hero.Lexi],
    languages: [Language.English],
    release: Release.LexiBlitzDeck,
    releaseDate: new Date("2021-11-24T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["lxi"],
    talents: [Talent.Elemental, Talent.Ice, Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    heroes: [Hero.Oldhim],
    languages: [Language.English],
    release: Release.OldhimBlitzDeck,
    releaseDate: new Date("2021-11-24T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["old"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice],
  },
  {
    cards: 238,
    classes: [Class.Guardian, Class.Ranger, Class.Runeblade],
    heroes: [Hero.Briar, Hero.Lexi, Hero.Oldhim],
    languages: [Language.English],
    release: Release.TalesOfAria,
    releaseDate: new Date("2021-09-24T00:00:00.000Z"),
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["ele"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice, Talent.Lightning],
  },
  {
    cards: 198,
    classes: [
      Class.Brute,
      Class.Guardian,
      Class.Illusionist,
      Class.Mechanologist,
      Class.Merchant,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    heroes: [Hero.GenisWotchuneed, Hero.Valda],
    languages: [Language.English],
    release: Release.Everfest,
    releaseDate: new Date("2022-02-04T00:00:00.000Z"),
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["evr"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice, Talent.Lightning],
  },
  {
    cards: 423,
    classes: [
      Class.Brute,
      Class.Guardian,
      Class.Mechanologist,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    heroes: [
      Hero.Azalea,
      Hero.Benji,
      Hero.Bravo,
      Hero.Dash,
      Hero.DataDoll,
      Hero.Dorinthea,
      Hero.Ira,
      Hero.Kassai,
      Hero.Katsu,
      Hero.Kayo,
      Hero.Rhinar,
      Hero.Viserai,
      Hero.Kano,
    ],
    languages: [Language.English],
    release: Release.HistoryPack1,
    releaseDate: new Date("2022-05-06T00:00:00.000Z"),
    releaseType: ReleaseType.HistoryPack,
    setIdentifiers: ["1hp", "hp1"],
    talents: [],
  },
  {
    cards: 80,
    classes: [Class.Brute, Class.Warrior],
    heroes: [Hero.Dorinthea, Hero.Rhinar],
    languages: [Language.English],
    release: Release.ClassicBattlesRhinarDorinthea,
    releaseDate: new Date("2022-05-27T00:00:00.000Z"),
    releaseType: ReleaseType.ClassicBattles,
    setIdentifiers: ["dvr", "rvd"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    heroes: [Hero.Dromai],
    languages: [Language.English],
    releaseDate: new Date("2022-06-24T00:00:00.000Z"),
    release: Release.DromaiBlitzDeck,
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["dro"],
    talents: [Talent.Draconic],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    heroes: [Hero.Fai],
    languages: [Language.English],
    release: Release.FaiBlitzDeck,
    releaseDate: new Date("2022-06-24T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["fai"],
    talents: [Talent.Draconic],
  },
  {
    cards: 226,
    classes: [Class.Illusionist, Class.Ninja, Class.Wizard],
    heroes: [Hero.Dromai, Hero.Fai, Hero.Iyslander],
    languages: [Language.English],
    release: Release.Uprising,
    releaseDate: new Date("2022-06-24T00:00:00.000Z"),
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["upr"],
    talents: [Talent.Draconic, Talent.Elemental, Talent.Ice],
  },
  {
    cards: 247,
    classes: [
      Class.Assassin,
      Class.Brute,
      Class.Guardian,
      Class.Illusionist,
      Class.Mechanologist,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    heroes: [Hero.Arakni, Hero.Emperor, Hero.Yoji],
    languages: [Language.English],
    release: Release.Dynasty,
    releaseDate: new Date("2022-11-11T00:00:00.000Z"),
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["dyn"],
    talents: [Talent.Royal],
  },
  {
    cards: 536,
    classes: [
      Class.Brute,
      Class.Guardian,
      Class.Illusionist,
      Class.Mechanologist,
      Class.Ninja,
      Class.Ranger,
      Class.Runeblade,
      Class.Warrior,
      Class.Wizard,
    ],
    heroes: [
      Hero.Boltyn,
      Hero.Briar,
      Hero.Chane,
      Hero.Levia,
      Hero.Lexi,
      Hero.Oldhim,
      Hero.Prism,
    ],
    languages: [
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: "History Pack 2: Black Label" as Release,
    releaseDate: new Date("2023-02-24T00:00:00.000Z"),
    releaseType: ReleaseType.HistoryPack,
    setIdentifiers: ["hp2"],
    talents: [
      Talent.Elemental,
      Talent.Earth,
      Talent.Ice,
      Talent.Lightning,
      Talent.Light,
      Talent.Shadow,
    ],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    heroes: [Hero.Arakni],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.ArakniBlitzDeck,
    releaseDate: new Date("2023-03-24T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ara"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ranger],
    heroes: [Hero.Azalea],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.AzaleaBlitzDeck,
    releaseDate: new Date("2023-03-24T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["azl"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    heroes: [Hero.Benji],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.BenjiBlitzDeck,
    releaseDate: new Date("2023-03-24T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ben"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    heroes: [Hero.Katsu],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.KatsuBlitzDeck,
    releaseDate: new Date("2023-03-24T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["kat"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Ranger],
    heroes: [Hero.Riptide],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.RiptideBlitzDeck,
    releaseDate: new Date("2023-03-24T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["rip"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    heroes: [Hero.Uzuri],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.UzuriBlitzDeck,
    releaseDate: new Date("2023-03-24T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["uzu"],
    talents: [],
  },
  {
    cards: 239,
    classes: [Class.Assassin, Class.Ranger, Class.Ninja],
    heroes: [
      Hero.Arakni,
      Hero.Uzuri,
      Hero.Azalea,
      Hero.Katsu,
      Hero.Benji,
      Hero.Riptide,
    ],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.Outsiders,
    releaseDate: new Date("2023-03-24T00:00:00.000Z"),
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["out"],
    talents: [],
  },
  {
    cards: 236,
    classes: [Class.Illusionist, Class.Runeblade, Class.Warrior, Class.Brute],
    heroes: [Hero.Prism, Hero.Vynnset, Hero.Boltyn, Hero.Levia],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.DuskTillDawn,
    releaseDate: new Date("2023-07-14T00:00:00.000Z"),
    releaseType: ReleaseType.ExpansionBooster,
    setIdentifiers: ["dtd"],
    talents: [Talent.Light, Talent.Shadow],
  },
  {
    cards: 107,
    classes: [Class.Mechanologist, Class.Bard, Class.Guardian, Class.Ninja],
    heroes: [Hero.Teklovossen, Hero.Melody, Hero.Brevant, Hero.Ira],
    languages: [Language.English],
    release: Release.RoundTheTable,
    releaseDate: new Date("2023-09-29T00:00:00.000Z"),
    releaseType: ReleaseType.RoundTheTable,
    talents: [],
    setIdentifiers: ["tcc"],
  },
  {
    cards: 251,
    classes: [Class.Mechanologist],
    heroes: [Hero.Dash, Hero.Maxx, Hero.Teklovossen],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.BrightLights,
    releaseDate: new Date("2023-10-06T00:00:00.000Z"),
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["evo"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    heroes: [Hero.Betsy],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.BetsyBlitzDeck,
    releaseDate: new Date("2024-02-02T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["bet"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Warrior],
    heroes: [Hero.Kassai],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.KassaiBlitzDeck,
    releaseDate: new Date("2024-02-02T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ksi"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Brute],
    heroes: [Hero.Kayo],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.KayoBlitzDeck,
    releaseDate: new Date("2024-02-02T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["kyo"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Warrior],
    heroes: [Hero.Olympia],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.OlympiaBlitzDeck,
    releaseDate: new Date("2024-02-02T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ola"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Brute],
    heroes: [Hero.Rhinar],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.RhinarBlitzDeck,
    releaseDate: new Date("2024-02-02T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["rnr"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    heroes: [Hero.Victor],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    release: Release.VictorBlitzDeck,
    releaseDate: new Date("2024-02-02T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["vic"],
    talents: [],
  },
  {
    cards: 255,
    classes: [Class.Brute, Class.Guardian, Class.Warrior],
    heroes: [Hero.Kassai, Hero.Betsy, Hero.Kayo, Hero.Olympia, Hero.Victor],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Spanish,
    ],
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.HeavyHitters,
    releaseDate: new Date("2024-02-02T00:00:00.000Z"),
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["hvy"],
    talents: [],
  },
  {
    cards: 66,
    classes: [Class.Brute],
    heroes: [Hero.Kayo],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckKayo,
    releaseDate: new Date("2024-05-03T00:00:00.000Z"),
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["ako"],
    talents: [],
  },
  {
    cards: 40,
    classes: [Class.Illusionist],
    heroes: [Hero.Enigma],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.EnigmaBlitzDeck,
    releaseDate: new Date("2024-05-31T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["eng"],
    talents: [Talent.Mystic],
  },
  {
    cards: 40,
    classes: [Class.Assassin],
    heroes: [Hero.Nuu],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.NuuBlitzDeck,
    releaseDate: new Date("2024-05-31T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["nuu"],
    talents: [Talent.Mystic],
  },
  {
    cards: 40,
    classes: [Class.Ninja],
    heroes: [Hero.Zen],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.ZenBlitzDeck,
    releaseDate: new Date("2024-05-31T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["zen"],
    talents: [Talent.Mystic],
  },
  {
    cards: 239,
    classes: [Class.Assassin, Class.Illusionist, Class.Ninja],
    heroes: [Hero.Enigma, Hero.Nuu, Hero.Zen],
    languages: ALL_LANGUAGES,
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.PartTheMistveil,
    releaseDate: new Date("2024-05-31T00:00:00.000Z"),
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["mst"],
    talents: [Talent.Mystic],
  },
  {
    cards: 66,
    classes: [Class.Warrior],
    heroes: [Hero.Boltyn],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckBoltyn,
    releaseDate: new Date("2024-07-12T00:00:00.000Z"),
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["asb"],
    talents: [Talent.Light],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    heroes: [Hero.Aurora],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.FirstStrikeAurora,
    releaseDate: new Date("2024-08-01T00:00:00.000Z"),
    releaseType: ReleaseType.FirstStrike,
    setIdentifiers: ["aur"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Guardian],
    heroes: [Hero.Terra],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.FirstStrikeTerra,
    releaseDate: new Date("2024-08-01T00:00:00.000Z"),
    releaseType: ReleaseType.FirstStrike,
    setIdentifiers: ["ter"],
    talents: [Talent.Earth],
  },
  {
    cards: 66,
    classes: [Class.Ranger],
    heroes: [Hero.Azalea],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckAzalea,
    releaseDate: new Date("2024-08-02T00:00:00.000Z"),
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["aaz"],
    talents: [],
  },
  {
    cards: 258,
    classes: [Class.Runeblade, Class.Wizard],
    heroes: [Hero.Aurora, Hero.Florian, Hero.Oscilio, Hero.Verdance],
    languages: ALL_LANGUAGES,
    raritiesExcludedInLimited: [Rarity.Legendary, Rarity.Fabled],
    release: Release.Rosetta,
    releaseDate: new Date("2024-09-20T00:00:00.000Z"),
    releaseType: ReleaseType.StandaloneBooster,
    setIdentifiers: ["ros"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    heroes: [Hero.Aurora],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.AuroraBlitzDeck,
    releaseDate: new Date("2024-09-20T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["aua"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Runeblade],
    heroes: [Hero.Florian],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.FlorianBlitzDeck,
    releaseDate: new Date("2024-09-20T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["flr"],
    talents: [Talent.Earth],
  },
  {
    cards: 40,
    classes: [Class.Wizard],
    heroes: [Hero.Oscilio],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.OscilioBlitzDeck,
    releaseDate: new Date("2024-09-20T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["osc"],
    talents: [Talent.Lightning],
  },
  {
    cards: 40,
    classes: [Class.Wizard],
    heroes: [Hero.Verdance],
    languages: [
      Language.English,
      Language.French,
      Language.German,
      Language.Italian,
      Language.Japanese,
      Language.Spanish,
    ],
    release: Release.VerdanceBlitzDeck,
    releaseDate: new Date("2024-09-20T00:00:00.000Z"),
    releaseType: ReleaseType.BlitzDeck,
    setIdentifiers: ["ver"],
    talents: [Talent.Earth],
  },
  {
    cards: 66,
    classes: [Class.Mechanologist],
    heroes: [Hero.Dash],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckDash,
    releaseDate: new Date("2024-10-18T00:00:00.000Z"),
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["aio"],
    talents: [],
  },
  {
    cards: 30,
    classes: [Class.Guardian],
    heroes: [Hero.Jarl],
    languages: [
      Language.English,
      Language.French,
      Language.Italian,
      Language.Japanese,
    ],
    release: Release.ArmoryDeckOriginsJarl,
    releaseDate: new Date("2024-11-29T00:00:00.000Z"),
    releaseType: ReleaseType.ArmoryDeck,
    setIdentifiers: ["ajv"],
    talents: [Talent.Elemental, Talent.Earth, Talent.Ice],
  },
];

export const fullSetIdentifiers: { [key: string]: Release } = {
  wtr: Release.WelcomeToRathe,
  arc: Release.ArcaneRising,
  cru: Release.CrucibleOfWar,
  mon: Release.Monarch,
  ele: Release.TalesOfAria,
  evr: Release.Everfest,
  "1hp": Release.HistoryPack1,
  hp1: Release.HistoryPack1,
  upr: Release.Uprising,
  dyn: Release.Dynasty,
  out: Release.Outsiders,
  dtd: Release.DuskTillDawn,
  evo: Release.BrightLights,
  hvy: Release.HeavyHitters,
  mst: Release.PartTheMistveil,
  ros: Release.Rosetta,
};

export const setIdentifierToSetMappings: { [key: string]: Release } = {
  ...fullSetIdentifiers,

  // Armory decks
  aaz: Release.ArmoryDeckAzalea,
  asb: Release.ArmoryDeckBoltyn,
  aio: Release.ArmoryDeckDash,
  ako: Release.ArmoryDeckKayo,
  ajv: Release.ArmoryDeckOriginsJarl,

  // Blitz decks
  ara: Release.ArakniBlitzDeck,
  aua: Release.AuroraBlitzDeck,
  azl: Release.AzaleaBlitzDeck,
  ben: Release.BenjiBlitzDeck,
  bet: Release.BetsyBlitzDeck,
  bol: Release.BoltynBlitzDeck,
  bri: Release.BriarBlitzDeck,
  chn: Release.ChaneBlitzDeck,
  dro: Release.DromaiBlitzDeck,
  eng: Release.EnigmaBlitzDeck,
  fai: Release.FaiBlitzDeck,
  flr: Release.FlorianBlitzDeck,
  kat: Release.KatsuBlitzDeck,
  ksi: Release.KassaiBlitzDeck,
  kyo: Release.KayoBlitzDeck,
  lev: Release.LeviaBlitzDeck,
  lxi: Release.LexiBlitzDeck,
  nuu: Release.NuuBlitzDeck,
  old: Release.OldhimBlitzDeck,
  ola: Release.OlympiaBlitzDeck,
  osc: Release.OscilioBlitzDeck,
  psm: Release.PrismBlitzDeck,
  rip: Release.RiptideBlitzDeck,
  rnr: Release.RhinarBlitzDeck,
  uzu: Release.UzuriBlitzDeck,
  ver: Release.VerdanceBlitzDeck,
  vic: Release.VictorBlitzDeck,
  zen: Release.ZenBlitzDeck,

  // 1st strike decks
  aur: Release.FirstStrikeAurora,
  ter: Release.FirstStrikeTerra,

  // Starter decks
  dvr: Release.ClassicBattlesRhinarDorinthea,
  rvd: Release.ClassicBattlesRhinarDorinthea,
  ira: Release.IraWelcomeDeck,

  // Other decks
  tcc: Release.RoundTheTable,

  // Hero decks
  bvo: Release.BravoHeroDeck,
  tea: Release.DorintheaHeroDeck,
  ksu: Release.KatsuHeroDeck,
  rnr2: Release.RhinarHeroDeck,

  // Promos
  fab: Release.Promos,
  her: Release.Promos,
  jdg: Release.Promos,
  lgs: Release.Promos,
  lss: Release.Promos,
  oxo: Release.Promos,
  xxx: Release.Promos,
  win: Release.Promos,
};

let tempSetToSetIdentifierMappings: { [key: string]: string[] } = {};
for (const [setIdentifier, set] of Object.entries(setIdentifierToSetMappings)) {
  const entry = tempSetToSetIdentifierMappings[set];
  if (entry) {
    entry.push(setIdentifier);
  } else {
    tempSetToSetIdentifierMappings[set] = [setIdentifier];
  }
}

export const setToSetIdentifierMappings = tempSetToSetIdentifierMappings;
