export const SPECIAL_USE_PROMOS: string[] = [
  "Brush of Heavenly Rites",
  "Brutus, Summa Rudis",
  "Cracker Bauble",
  "Diamond Hands",
  "Fabric of Blossoms",
  "Fabric of Hope",
  "Fabric of Providence",
  "Fabric of Scales",
  "Fabric of Spring",
  "Frankie, Make Ends Meat",
  "Gavel of Natural Order",
  "Go Bananas",
  "Good Deeds Don't Go Unnoticed",
  "Hummingbird, Call of Adventure",
  "Magrar",
  "Off Cuts",
  "Pink Visor",
  "Popped Collar Polo",
  "Proclamation of Abundance",
  "Proclamation of Combat",
  "Proclamation of Production",
  "Proclamation of Requisition",
  "Ruu'di, Gem Keeper",
  "Scarf for a Scarf",
  "Shitty Xmas Present",
  "Silversheen Needle",
  "Squizzy & Floof",
  "Spirit of Christmas",
  "Taipanis, Dracai of Judgement",
  "Tales of Adventure",
  "Taylor",
  "Theryon, Magister of Justice",
  "Venomback Fabric",
  "Yorick, Weaver of Tales",
];
